#!/usr/bin/env bash
# This script transfers a file from a client to a server using SCP.

# Check if correct number of parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using SCP
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/

# Check if SCP command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Failed to transfer file."
fi
