#!/usr/bin/env bash
# Bash script to configure Nginx redirection on a new Ubuntu machine

# Update
apt-get update

# Install Nginx
apt-get install nginx -y

# Configure Nginx redirection
echo '
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Other server configurations...
}
' | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
service nginx restart

# Output confirmation message
echo "Nginx redirection configured successfully. /redirect_me is now redirected to another page./"
