#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu machine to serve a "Hello World" page at the root, set up a redirection, and configure a custom 404 error page.

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Start Nginx service
sudo service nginx start

# Configure "Hello World" page
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Modify the Nginx default server block configuration
sudo sed -i '/^server {/a \\tlocation /redirect_me { return 301 https://google.com; }\n' /etc/nginx/sites-available/default
sudo sed -i '/^server {/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html { root /usr/share/nginx/html; internal; }\n' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
