#!/usr/bin/env bash
# Init script for managing manage_my_process

pid_file="/var/run/my_process.pid"
script="./manage_my_process"

start() {
    if [ -f "$pid_file" ]; then
        echo "manage_my_process is already started."
    else
        nohup $script > /dev/null 2>&1 &
        echo $! > "$pid_file"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        rm -f "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
