#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process without using kill or killall.

# Fint PID of the process
pid=$(pgrep -fo "4-to_infinity_and_beyond")

# Check if process if running
if [ -n "$pid" ]; then
    echo "Stopping 4-to_infinity_and_beyond..."
    # Send interrupt signal to gracefully stop the process
    kill -INT "$pid"
else
    echo "4-to_infinity_and_beyond is not running."
fi
