#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely with a sleep of 2 seconds.
# Display "I am invincible!!!" on receiving a STGTERM signal.

trap 'echo "I am invincible!!!"' STGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
