#!/usr/bin/env bash
# Displays "Best School" 10 times, saying "Hi" on the 9th iteration.

counter=0

while [ $counter -lt 10 ]; do
  if [ $counter -eq 9 ]; then
    echo "Hi"
  else
    echo "Best School"
   fi

   ((counter++))
done
