#!/usr/bin/env bash
# Script to display all active IPv4 IPs in the machine

# Use the 'ip' commnand to get the active IPs
ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Display the active IPs
echo "$ips"
