#!/usr/bin/env bash
# Fix Apache configuration to serve page containing "Hello Holberton"

# Install Apache if not already installed
apt-get update
apt-get install -y apache2

# Create an HTML file containing "Hello Holberton" place it in root directory
echo "Hello Holberton" > /var/www/html/index.html

# Restart Apache service
service apache2 restart
