#!/usr/bin/env bash
# This script runs the whoami command under user, passed as argument

# Check if the number of arguments is exactly one
if [ "$#" -ne 1]; then
    echo "Usage: %0 <username>"
    exit 1
fi

# Run whoami command under the specified user
sudo -u "$1" whoami
