#!/usr/bin/env bash
# This script creates an RSA key pair

# Define the filename for the private key
private_key="school"

# Define the number of bits for the key
bits=4096

# Define the passphrase
passphrase="betty"

# Generate the RSA key pair with the specified parameters
ssh-keygen -t rsa -b $bits -f "$private_key" -N "$passphrase"

# Output success message
echo "RSA key pair created successfully."
